<a href="https://colab.research.google.com/github/solozano0725/diplomadoMLNivel1/blob/main/DipMLsesion5.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

<p><img alt="Colaboratory logo" height="140px" src="https://upload.wikimedia.org/wikipedia/commons/archive/f/fb/20161010213812%21Escudo-UdeA.svg" align="left" hspace="10px" vspace="0px"></p>

# **Diplomado de Análisis de datos y Machine Learning en Python**


El presente diplomado hace parte del centro de Big Data de la facultad de ciencias exactas y naturales (FCEN) de la Universidad de Antioquia.

## **Sesión 5**

## **Contenido**
  
- <a href="#fun"> Funciones</a><br>
  - <a href="#lon"> Argumentos de longitud variable</a><br>
  - <a href="#lam"> Funciones anónimas</a><br>
- <a href="#num"> NumPy</a><br>
  - <a href="#arr"> Arreglos en NumPy</a><br>
  - <a href="#ope"> Operaciones sobre los arreglos</a><br>


- <a href="#apeA"> Apéndice: Iteradores útiles</a><br>






<p><a name="lon"></a></p>

## **Argumentos de longitud variable**

Es posible que necesitemos ejecutar una función en la que en principio no sabemos cuántos argumentos se pasarán a la función. En este caso, podemos utilizar una clase especial de argumentos, denominados argumentos de longitud variable, con los que podemos capturar todos los argumentos que se pasen a la función.

Por ejemplo, en el caso de la funcion `print`, esta admite un número arbitrario de argumentos para imprimirlos en pantalla



In [ ]:
print(1, 2, 3)

print(1, 2, 3, 4, 5)

...

**args**: El argumento de longitud variable `*args` permite capturar una serie de argumentos sin necesidad de especificar en un principio su número.

Escribamos una función que simule la función `print` para ver cómo debemos definir este tipo de argumentos.

In [ ]:
def my_print(*args):
  print(args)

my_print(1,2)

(1, 2)


Lo importante aquí no es el nombre `args`, sino el caracter `*` que lo precede. `args` es solo el nombre que se usa por convención. Un solo `*` antes de una variable significa *expandir esto como una secuencia*. En este caso particular, note que `args` se expande como una *tupla*. Iteremos esta tupla dentro de la función para mostrar cada elemento de la tupla individualmente




In [ ]:
def my_print(*args):
  for arg in args:
    print(arg)

my_print(1, 2, 3)

1
2
3


De hecho, esta sintáxis puede utilizarse no solo en la definición de la función, sino también a la hora de llamar la función. 

Supongamos que tenemos la lista `[1, 2, 3]` y queremos pasar cada uno de los elementos de forma individual a la función print (no como lista). En ese caso escribiríamos:

In [ ]:
l = [1, 2, 3]

print(l[0], l[1], l[2])

1 2 3


Utilizando la sintáxis anterior tendríamos:

In [ ]:
print(*l) #equivalente a print(l[0], l[1], l[2]) 

1 2 3


Podemos aprovecharnos de este hecho para modificar la función `my_print` a la hora de la llamada de la función `print`:

In [ ]:
def my_print(*args):
  print(*args)

my_print(*l)

1 2 3


Cabe resaltar que la llamada de una función con esta sintáxis funciona independientemente de si se ha declarado la función con `*args` o no. Veamos un ejemplo:

In [ ]:
# definicion de la funcion
def suma(a, b):
  return a+b

In [ ]:
# llamada de la funcion utilizando *
l = [1, 1]

suma(*l)

2

Podemos aprovecharnos de esta funcionalidad para generar listas rápidamente a partir de objetos iterables (sin utilizar el constructor `list`)

In [ ]:
# objeto iterable (no es una lista)
range(2)

range(0, 2)

In [ ]:
# conversion a lista
list(range(2))

[0, 1]

In [ ]:
# equivalentemente
[*range(2)]

[0, 1]

**Ejercicio 1:** Escriba un programa que calcule el promedio de n números enteros.

In [ ]:
def promedio(*numeros):
  """
  retorna el promedio de un 
  numero arbitrario de numeros
  """
  return sum(numeros)/len(numeros)

In [ ]:
# tomando multiples numeros por parte
# de un usuario externo
n = int(input("¿Cuantos numeros desea ingresar?: "))

print(f"Ingrese los {n} numeros")
nums = [int(input()) for _ in range(n)]

print(f"El promedio es: {promedio(*nums)}")

**kwargs**: Al igual que con `*args`, podemos utilizar el argumento por longitud variable `*kwargs` para capturar un número indefinido de argumentos por palabra clave. 

Un doble `**` antes de una variable significa *expandir esto como un diccionario*

In [ ]:
def my_print(*args, **kwargs):
  print(*args, **kwargs)

my_print(1, 2, sep=",")

1,2


de forma análoga al caso anterior, podemos utilizar esta sintáxis a la hora de llamar la función:

In [ ]:
dic = dict(sep=",")

my_print(1, 2, **dic)

1,2


<p><a name="lam"></a></p>

# **Funciones Anónimas**

Estas funciones no se declaran de la manera estándar utilizando la palabra clave `def`. Podemos usar la palabra clave `lambda` para crear pequeñas funciones anónimas en una sola línea. La sintáxis general es de la forma:

> 

    lambda arg1, arg2, ... : expresion(arg1, arg2, ...)

Por ejemplo, la función `suma` que definimos anteriormente

In [ ]:
def suma(a, b):
  return a+b

print(suma)

<function suma at 0x7ff895101830>


Tomaría la forma

In [ ]:
suma = lambda x, y: x + y 

print(suma)

<function <lambda> at 0x7ff895086560>


Note la equivalencia entre ambas sintáxis. 

La función creada de forma estándar tiene como nombre `suma`, mientras que la función anónima tiene como nombre `<lambda>` y no `suma`, de ahí que se conozcan como *funciones anónimas*.

Con esta nueva sintáxis podemos utilizar los argumentos requeridos y los argumentos por palabra clave, así como los argumentos de longitud variable

In [ ]:
my_print = lambda *args, **kwargs: print(*args, **kwargs)

In [ ]:
my_print(1, 2, 3, sep="|")

1|2|3


<p><a name="num"></a></p>

# **NumPy** 

**Variable en C**

![variables in C](https://i.imgur.com/0RQOTQ0.png)

La implementación estándar de Python está escrita en C. Esto significa que cada objeto de Python es simplemente una estructura de C, que contiene no solo su valor, sino también otra información.

Ya hemos visto que cuando definimos una variable en Python, esta es en realidad un puntero (a una estructura compuesta de C), que contiene ciertos valores diferentes: referencia, tipo, tamaño, valor, etc.

**Variable en Python**

![](https://i.imgur.com/F3IQqwE.png)

Esta característica de Python lo hacen un lenguaje de *tipado dinámico*, de tal manera que no tenemos que definir el tipo de las variables. Por ejemplo, podemos generar listas donde cada uno de sus elementos pueden ser de cualquier tipo:

In [ ]:
L = [True, "2", 3.0, 4]

[type(i) for i in L]

[bool, str, float, int]

Esta flexibilidad tiene un costo: cada elemento de la lista debe contener su propia información, es decir, cada elemento es un objeto completo de Python. En el caso especial en que todas las variables sean del mismo tipo, gran parte de esta información es redundante: puede ser mucho más eficiente almacenar datos en una lista de un tipo homogéneo. 

Python ofrece diferentes opciones para almacenar datos de esta manera (por ejemplo a través del módulo `array`). Sin embargo, la mejor manera de generar este tipo de objetos es a través de la libreria NumPy.



**Numpy (Numerical Python)**

En el núcleo de la mayoría de los problemas encontramos un **arreglo**. Desde el punto de vista computacional, un arreglo es un bloque contiguo de memoria donde cada elemento tiene el mismo tipo.

Los diferentes lenguajes de programación utilizados en computación científica tienen alguna noción de manejo de datos basado en arreglos, ya sea integrado en el lenguaje propio o a través de paquetes proporcionados por terceros.

NumPy es el paquete fundamental para la computación científica en Python. Es una libreria que proporciona herramientas para la generación de arreglos y una variedad de funcionalidades para realizar operaciones sobre estos, que generalmente se realizan de una manera más eficiente que lo que se puede lograr con funcionalidades propias de Python. NumPy sirve como bloque básico para una gran cantidad de paquetes científicos y de análisis de datos:





<p><img alt="Colaboratory logo" height="640px" src="https://media.springernature.com/full/springer-static/image/art%3A10.1038%2Fs41586-020-2649-2/MediaObjects/41586_2020_2649_Fig2_HTML.png?as=webp" align="left" hspace="10px" vspace="0px"></p>

<p><a name="arr"></a></p>

# **Arreglos en Numpy**

En el núcleo de NumPy, está el objeto `ndarray` (n-dimensional array). Este encapsula **arreglos n-dimensionales** de tipos de datos homogéneos, con muchas **operaciones que se realizan en código compilado**, con lo cual se mejora el rendimiento significativamente. 

La diferencia entre una lista de tipo dinámico y un arreglo de tipo fijo (al estilo NumPy) se ilustra en la siguiente figura:

<p><img alt="Colaboratory logo" height="350px" src="https://i.imgur.com/8EbyB0c.png" align="left" hspace="10px" vspace="0px"></p>

Al nivel de implementación, el arreglo contiene esencialmente un puntero único a un bloque contiguo de datos. La lista de Python, por otro lado, contiene un puntero a un bloque de punteros, cada uno de los cuales a su vez apunta a un objeto completo de Python como el entero de Python que vimos anteriormente.

En resumen, estas son las diferencias más importantes entre los arreglos de NumPy y las secuencias estándar de Python:

* Todos los elementos en un arreglo de NumPy deben ser del mismo tipo de dato y, por lo tanto, tendrán el mismo tamaño en memoria.
* Los arreglos de NumPy tienen un tamaño fijo en la creación, a diferencia de las listas de Python (que pueden crecer dinámicamente). Cambiar el tamaño de un `ndarray` creará un nuevo arreglo y eliminará el original.
* Los arreglos de NumPy facilitan operaciones avanzadas matemáticas y de otro tipo en grandes cantidades de datos. Típicamente, tales operaciones se ejecutan de manera más eficiente que usando las secuencias integradas de Python.





Por convención, la librería NumPy se import con el alias `np`

In [ ]:
import numpy as np

Podemos construir un objeto `ndarray`, a partir de una lista de Python, mediante el constructor `array`:


In [ ]:
x = np.array([1, 2, 3, 4])
x

array([1, 2, 3, 4])

In [ ]:
type(x)

numpy.ndarray

El objeto `ndarray` representa efectivamente un bloque de memoria de tamaño fijo, el cual contiene una serie de atributos y métodos que definen su estructura. Veamos algunos de los atributos más importantes de este objeto:



**dtype:** 

Este determina el tipo de dato de cada elemento del arreglo. El sistema predeterminado de *dtypes* que proporciona NumPy es más preciso y más amplio para los tipos básicos que el sistema de tipos que implementa el lenguaje Python

In [ ]:
x.dtype

dtype('int64')

<p><img alt="Colaboratory logo" height="400px" src="https://i.imgur.com/2RpU9w1.png" align="left" hspace="10px" vspace="0px"></p>

Podemos definir el tipo de dato a la hora de la creación del arreglo utilizando el kwarg `dtype`

In [ ]:
np.array([1, 2, 3], dtype="int8")

array([1, 2, 3], dtype=int8)

**shape:** 

Tupla de enteros que representa el rango a lo largo de cada dimensión de los arreglos n-dimensionales.

<p><img alt="Colaboratory logo" height="400px" src="https://i.imgur.com/Bbs8Ijp.png" align="left" hspace="10px" vspace="0px"></p>


In [ ]:
# arreglo
x

array([1, 2, 3, 4])

In [ ]:
# forma del arreglo
x.shape

(4,)

La forma `(4,)`, nos dice que `x` es un arreglo unidimensional, donde la dimensión tiene un rango 4. La dimensión y el número de elementos del arreglo se pueden obtener mediante los atributos `ndim` y `size`, respectivamente:

In [ ]:
# dimension del arreglo
x.ndim

1

In [ ]:
# numero de elementos del arreglo
x.size

4

Podemos modificar la forma del arreglo modificando el atributo `shape` directamente

In [ ]:
x.shape = (2,2)
x

array([[1, 2],
       [3, 4]])

Alternativamente, NumPy proporciona el método `reshape`, con el cual podemos cambiar la forma de un arreglo. Este toma como argumento el arreglo a modificar y un entero o tupla que represente la nueva forma. Esta nueva forma debe ser compatible con el número de elementos que tenga el arreglo. 

Cambiemos la forma de `x` para tener un *vector columna*:

In [ ]:
# vector columna a partir de x
np.reshape(x, (4,1))

array([[1],
       [2],
       [3],
       [4]])

Note que en este caso utilizamos pasamos el arreglo como argumento de la función `np.reshape`. Alternativamente, podemos utilizar esta función como si fuera un método del arreglo:

In [ ]:
# vector columna a partir de l
x.reshape(4,1)

array([[1],
       [2],
       [3],
       [4]])

NumPy nos permite pasar una de las dimensiones como `-1`. De esta manera, Numpy se encargará de que el rango en esa dimensión sea compatible con el arreglo original y con el rango de la dimensión que se fijó:

In [ ]:
# fijando el numero de filas
x.reshape(4,-1)

array([[1],
       [2],
       [3],
       [4]])

In [ ]:
# fijando el numero de columnas
x.reshape(-1,4)

array([[1, 2, 3, 4]])

Note que el método `reshape` es simplemente una vista del arreglo original (una copia), por lo que no se ha modificado su forma:

In [ ]:
x

array([[1, 2],
       [3, 4]])

Si queremos cambiar la forma del arreglo podemos modificar directamente el atributo `shape` o redefinir el arreglo con `reshape` como ya hemos visto en otros contextos.

**Formas alternativas de construir arreglos:** 

NumPy proporciona formas alternativas de crear arreglos. Las funciones más comunes son `arange`, `linspace` `zeros`, `ones`, `full` y `empty`. 

* La función `arange()` toma un inicio, final y un paso como la función `range()` de Python, excepto que devuelve un `ndarray` y que el paso puede ser un número real

> 
    np.arange(inicio, final, paso)

In [ ]:
# arreglo de 1 a 9 con paso 2
np.arange(1,10,2)

array([1, 3, 5, 7, 9])

In [ ]:
# arreglo de 1 a 9 con paso 1.5
np.arange(1,10,1.5)

array([1. , 2.5, 4. , 5.5, 7. , 8.5])

- La función `linspace` crea una serie de puntos uniformemente entre un límite inferior y superior que incluye ambos extremos. Su sintáxis es de la forma:

> 
    np.linspace(inicio, final, numero de puntos)

In [ ]:
# arreglo de -1 a 1 con 10 puntos
np.linspace(-1, 1, 10)

array([-1.        , -0.77777778, -0.55555556, -0.33333333, -0.11111111,
        0.11111111,  0.33333333,  0.55555556,  0.77777778,  1.        ])

- Las funciones `zeros()` y `ones()` toman un entero o una tupla de enteros como argumento y devuelven un `ndarray` cuya forma coincide con la de la tupla y cuyos elementos son cero o uno:

In [ ]:
# crear un arreglo de forma (2,2) llenado con ceros
np.zeros((2,2))

array([[0., 0.],
       [0., 0.]])

In [ ]:
#crear un arreglo de forma (5,) llenado con unos
np.ones(5)

array([1., 1., 1., 1., 1.])

- La función `full()` funciona de manera similar a `zeros()` y `ones()`, solo que podemos llenar el arreglo con cualquier valor:

In [ ]:
#crear un arreglo de forma (2,2) llenado con pi
np.full((2,2), np.pi)

array([[3.14159265, 3.14159265],
       [3.14159265, 3.14159265]])

- La función `empty()`, por otro lado, asignará memoria sin asignarle ningún valor. Esto significa que el contenido de un arreglo vacío será lo que esté en la memoria en ese momento. Esto es particularmente útil cuando creamos un arreglo cuyos valores serán modificados posteriormente.

In [ ]:
#crear un arreglo de 4 elementos 
np.empty(4)

array([3.14159265, 3.14159265, 3.14159265, 3.14159265])

* En muchas ocaciones vamos a necesitar construir arreglos cuyos elementos se generen de forma aleatoria. En estos casos podemos utilizar el submódulo random de la librería.

  * La función `random.rand` genera un arreglo cuyos elementos se muestrean de una distribución uniforme en el intervalo (0,1).

    `np.random.rand(shape)`


In [ ]:
# arreglo aleatorio de forma (3,3) con números 
# de punto flotante en el intervalo (0,1)
np.random.rand(3,3)

array([[0.62999901, 0.3244386 , 0.99671175],
       [0.00980343, 0.11953916, 0.48298577],
       [0.37776994, 0.6036433 , 0.99450062]])

  * La función `random.randint` genera un arreglo aleatorio de números enteros en un rango especifico con una forma dada:

  `np.random.randint(limite_inferior, limite_superior, shape)`

In [ ]:
# arreglo aleatorio de forma (2,2) con números
# enteros en el intervalo (10,20) 
np.random.randint(10, 20, (3,3))

array([[14, 11, 15],
       [19, 10, 17],
       [10, 12, 17]])

<p><a name="ope"></a></p>

# **Operaciones sobre los arreglos**

Ahora que hemos visto cómo definir arreglos de NumPy, podemos discutir cómo realizar operaciones sobre los arreglos. La clave para hacer estas operaciones de una forma rápida y eficiente es usar operaciones **vectorizadas**, implementadas a través de las funciones universales de NumPy (ufuncs).

Recordemos que la operación de sumar dos listas de Python resulta en la concatenación de dichas listas:



In [ ]:
# python
l1 = [1, 2, 3]
l2 = [4, 5, 6]

l1+l2

[1, 2, 3, 4, 5, 6]

Si quisieramos sumar elemento a elemento, debemos hacer explícito un ciclo `For` de la siguiente manera (**ver Apéndice**):

In [ ]:
# Python
l1 = [1, 2, 3]
l2 = [4, 5, 6]

[i+j for i,j in zip(l1, l2)]

[5, 7, 9]

Si realizamos esta misma operación con arreglos de Numpy, obtendremos otra salida:

In [ ]:
# numpy
l1 = np.array([1, 2, 3])
l2 = np.array([4, 5, 6])

l1+l2

array([5, 7, 9])

Como los arreglos son de NumPy, se está realizando lo que se conoce como una operación **vectorizada**, la cual es una operación sobre los arreglos que se realiza **elemento a elemento**, mediante lo que conocemos como funciones universales (ufuncs) de Numpy. 

Las ufuncs de NumPy se sienten muy naturales de usar porque hacen uso de los operadores aritméticos nativos de Python. 

La siguiente tabla nos muestra algunas de las funciones universales disponibles en Numpy (ver [documentación](https://numpy.org/doc/stable/reference/ufuncs.html#ufunc))





 

![picture](https://i.imgur.com/8HaZzxg.png)

Note que estas se muestran en dos versiones: mediante un operador y su correspondiente función universal. Por ejemplo `+` y `np.add`. 

Como en el ejemplo anterior, si los arreglos son de NumPy, el operador que utilicemos para realizar las operaciones representará la función universal. Si el arreglo no se define como uno de NumPy, y si queremos aplicar una función universal, debemos utilizar la forma explícita de la función universal

In [ ]:
# utilizando la ufunc explicitamente
l1 = [1, 2, 3]
l2 = [4, 5, 6]

np.add(l1, l2)

array([5, 7, 9])

En el caso de la multiplicacion en Python, la multiplicación de un número entero `n` por una lista `l`, nos "multiplica" la lista `l` `n` veces:



In [ ]:
# Python
n = 2
l = [1, 2, 3]

n*l

[1, 2, 3, 1, 2, 3]

Si quisieramos multiplicar el número `n` por cada uno de los elementos de la lista `l` debemos incluir, al igual que en el caso de la suma, un ciclo `For` de forma explícita

In [ ]:
[n*elemento for elemento in l]

[2, 4, 6]

Alternativamente podemos utilizar la función `map`, que toma como argumento una función `f` y una secuencia `s`, y nos devuelve un objeto iterable donde se le aplica la función `f` a cada uno de los elementos de `s`.

Definamos la función como una función anónima y pasemos la lista `l`:

In [ ]:
[*map(lambda x: n*x, l)]

[2, 4, 6]

Adicionalmente, la operación de multiplicación entre listas no está definida en Python

In [ ]:
l1 = [1, 2, 3]
l2 = [4, 5, 6]

l1*l2

TypeError: ignored

En NumPy, ambas operaciones se hacen de forma vectorizada:

In [ ]:
# multiplicacion por una constante
l = np.array([1, 2, 3])

n*l

array([2, 4, 6])

In [ ]:
# multiplicacion de arreglos
l1 = np.array([1, 2, 3])
l2 = np.array([4, 5, 6])

l1*l2

array([ 4, 10, 18])

Note que ambas operaciones se hacen elemento a elemento, caracteristica de las operaciones vectorizadas implementadas a través de ufuncs. 

NumPy también incluye funciones para realizar operaciones de álgebra lineal. En el caso de la multiplicación de arreglos, la salida no corresponde a lo que conocemos como producto punto. Para realizar esta operación, tanto en arreglos unidimensionales como n-dimensionales, podemos utilizar la función universal `np.dot` o su operador asociado `@`:



In [ ]:
# producto punto entre vectores
l1 = np.array([1, 2, 3])
l2 = np.array([4, 5, 6])

l1@l2

32

In [ ]:
# producto punto entre matrices
A = np.arange(9).reshape(3,3)

A@A

array([[ 15,  18,  21],
       [ 42,  54,  66],
       [ 69,  90, 111]])

También podemos obtener el "producto cruz" con la función `cross`

In [ ]:
# producto cruz
a = np.array([1, 0, 0])
b = np.array([0, 1, 0])

np.cross(a, b)

array([0, 0, 1])

Otras funcionalidades:

In [ ]:
# determinante
np.linalg.det(A)

0.0

In [ ]:
# matriz identidad
I = np.identity(3)
I

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [ ]:
# inversa
np.linalg.inv(I)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

# **Funciones de agregación**

Las funciones de agregación son funciones en las que un conjunto de elementos se agrupan para formar un único valor "de resumen". Las siguientes son algunas de las funciones de agregación que podemos implementar con NumPy:



<p><img alt="Colaboratory logo" height="400px" src="https://i.imgur.com/eaPmQPb.png" align="left" hspace="10px" vspace="0px"></p>

Este tipo de operaciones pueden implementarse independientemente en cada una de las dimensiones del arreglo. Veamos un ejemplo con el arreglo `A` que definimos anteriormente:

In [ ]:
A

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
# sumando todos los elementos
np.sum(A) 

36

In [ ]:
# sumando los elementos a traves
# del eje 0 (por columna)
np.sum(A, axis=0)

array([ 9, 12, 15])

In [ ]:
# sumando los elementos a traves
# del eje 1 (por fila)
np.sum(A, axis=1)

array([ 3, 12, 21])

Note que también se incluyen funciones de agregación para *valores nulos*, que en Numpy se representan como `nan` (not a number)

In [ ]:
# valor nulo en numpy
np.nan

nan

In [ ]:
np.nansum(np.array([np.nan, 1, 2]))

3.0

Note que si aplicaramos una función de agregación "normal", obtendríamos un valor nulo

In [ ]:
np.sum(np.array([np.nan, 1, 2]))

nan

**Ejercicio 2**: Escriba un programa para crear un nuevo arreglo que sea el promedio de cada triplete consecutivo de elementos del siguiente arreglo

<p><img alt="Colaboratory logo" height="70px" src="https://i.imgur.com/XoHovZd.png" align="left" hspace="10px" vspace="0px"></p>

In [ ]:
# definimos el arreglo
a = np.array([1,2,3,2,4,6,1,2,12,0,-12,6])

# modificamos su forma 
print("Arreglo modificado al que se le aplica la funcion de agregacion")
print(a.reshape(4,-1))

# de tal manera que podamos aplicar
# la funcion de agregacion mean por filas
print("Promedio de cada triplete consecutivo")
print(np.mean(a.reshape(4,-1), axis=1))

Arreglo modificado al que se le aplica la funcion de agregacion
[[  1   2   3]
 [  2   4   6]
 [  1   2  12]
 [  0 -12   6]]
Promedio de cada triplete consecutivo
[ 2.  4.  5. -2.]


<p><a name="apeA"></a></p>

# **Apéndice: Iteradores útiles**

A menudo vamos a necesitar iterar los diferentes objetos de diversas formas, por lo que vamos a requerir de iteradores que nos permitan tener más libertad a la hora de definir las iteraciones. Veamos algunos de estos iteradores disponibles en Python.

Por ejemplo, si quisieramos iterar sobre una lista de manera que la variable de iteración corra de forma ordenada sobre los elementos, es decir, no sobre los elementos de acuerdo a su posición en la lista sino de acuerdo a su valor numérico, podemos utilizar el método `sorted` sobre la lista:

In [ ]:
L = [5, 2, 7, 1]

for i in sorted(L):
  print(i)

1
2
5
7


Ahora, supongamos que necesitamos iterar sobre los elementos de una lista y además tener registro del índice del elemento. Podríamos escribir algo como:


In [ ]:
L = range(4,8)

for i in range(len(L)):
  print(f"indice: {i} valor: {L[i]}")

indice: 0 valor: 4
indice: 1 valor: 5
indice: 2 valor: 6
indice: 3 valor: 7


Podemos realizar esta iteración de una forma más simple y elegante utilizando el iterador `enumerate`, que produce un generador de tuplas con los índices y valores de la lista:

In [ ]:
list(enumerate(L))

[(0, 4), (1, 5), (2, 6), (3, 7)]

In [ ]:
for indice, valor in enumerate(L):
  print(f"indice: {indice} valor: {valor}")

indice: 0 valor: 4
indice: 1 valor: 5
indice: 2 valor: 6
indice: 3 valor: 7


En otras ocaciones, vamos a querer iterar sobre varias listas simultáneamente. Una forma directa de hacerlo sería iterando sobre el índice de las listas 


In [ ]:
l = range(2,4)
r = range(6,8)

for i in range(len(l)):
  print(f"l: {l[i]}, r: {r[i]}")

l: 2, r: 6
l: 3, r: 7


Si, por ejemplo, cambiaramos la longitud de `l`, obtendríamos un error

In [ ]:
l = range(2,5)
r = range(6,8)

for i in range(len(l)):
  print(f"l_val: {l[i]}, r_val: {r[i]}")

l_val: 2, r_val: 6
l_val: 3, r_val: 7


IndexError: ignored

esta iteración se puede llevar a cabo mediante el iterador `zip`, que permite iterar sobre varios objetos iterables simultáneamente:

In [ ]:
list(zip(l, r))

[(2, 6), (3, 7)]

In [ ]:
for lval, rval in zip(l, r):
  print(f"l: {lval}, r: {rval}")

l: 2, r: 6
l: 3, r: 7


`zip` produce un generador de tuplas obtenidas a partir de los objetos iterables que pasemos como argumento. Tenga en cuenta que el iterador admite objetos de diferente tipo para la iteración 

In [ ]:
for i,j in zip(range(3), "abc"):
  print(i,j)

0 a
1 b
2 c


así como objetos de tamaños diferentes

In [ ]:
for i,j,k in zip((1,2,3), "abc", [4,5,6,7]):
  print(i,j,k)

1 a 4
2 b 5
3 c 6


Note que las tuplas se producen con una longitud tal que coincida con el número de elementos del objeto de menor longitud.